Minimal validation of input XML
oasis-tcs/odata-csdl-schemas pull request #50
Opened 2021-12-03 15:04 UTC by ralfhandl

2021-12-03 15:37 UTC, HeikoTheissen reviewed
Unexpected attributes go undetected on elements that don't expect any. I have added code for the `Null` element, but there are others.

2021-12-06 07:57 UTC, ralfhandl commented
@HeikoTheissen Good catch, will add similar code in all other cases.

2021-12-06 13:51 UTC, HeikoTheissen requested changes

2021-12-06 13:51 UTC, HeikoTheissen commented on test/xml2json.test.js
> +        "Element: edmx:Include, unexpected attribute: alias"
```suggestion
        "Element Include, unexpected attribute: alias"
```

2021-12-06 13:51 UTC, HeikoTheissen commented on lib/xml2json.js
> +          `Element: ${node.name}, unexpected attribute: ${attribute.name}`
```suggestion
          `Element ${node.local}, unexpected attribute: ${attribute.name}`
```
Elsewhere, element names in error messages are not prefixed.

2021-12-06 14:27 UTC, HeikoTheissen approved these changes

2021-12-06 14:28 UTC, merged